# run_log.ps1 - capture one RUN from the car and print a scorecard (+ optional CSV).
#
#   Works over the WIRED port (DAP VCOM) or the WIRELESS bridge port - it is just a COM port
#   either way, so nothing here is wireless-specific. Wireless is the interesting case though:
#   that is when the car is untethered and this is your only view of it.
#
# WHY THIS EXISTS
#   Reading telemetry with read_serial.ps1 gives you 100 lines of text. What you actually want
#   after a run is: did we lose packets, how straight did it go, how far did each wheel turn,
#   how much did yaw drift. That is a table, and the report/defence needs exactly that table
#   (the national-award report we studied has 4 of them). So: capture -> parse -> metrics.
#
# REAL PACKET LOSS (this is the point of the firmware's #<seq> field)
#   Wireless is UDP, no retransmit: whatever is lost while the car is out of range is GONE.
#   Without a line number you cannot tell "link dropped" from "car was not moving" - the most
#   dangerous ambiguity when reading the data afterwards. With #<seq>:
#       loss% = 1 - received / (last_seq - first_seq + 1)
#   That is TRUE loss, not "did the line count match what I expected".
#
# WHY dt USES THE FIRMWARE TIMESTAMP (t<ms>) AND NOT THE PC CLOCK
#   Measured on this link: single-line arrival gaps range 0..187 ms and 6.9% arrive <=2 ms apart
#   (several telemetry lines packed into one UDP datagram). So PC-side timestamps are fine for
#   "rate / trend" and useless for precise dt. t<ms> is generated by the SysTick time base.
#
# USAGE
#   powershell -NoProfile -ExecutionPolicy Bypass -File run_log.ps1 -Port COM4 -Seconds 20
#   powershell -NoProfile -ExecutionPolicy Bypass -File run_log.ps1 -Port COM4 -Seconds 20 -Csv run1.csv
#
# EXIT CODE / RESULT is three-state on purpose (repo convention):
#   PASS         - enough samples and loss under -MaxLossPct
#   FAIL         - loss over the limit
#   INCONCLUSIVE - too few samples to say anything (do NOT read this as "no problem")
#
# ASCII only on purpose (Windows PowerShell 5.1 mangles non-ASCII inside script files).
param(
    [string]$Port       = "COM4",
    [int]$Baud          = 115200,
    [int]$Seconds       = 15,
    [string]$Csv        = "",        # empty = do not write a CSV
    [double]$MaxLossPct = 5.0,
    [int]$MinSamples    = 10,
    [string]$Out        = "run_log_out.txt"
)

$log = New-Object System.Text.StringBuilder
function L([string]$s) { [void]$log.AppendLine($s); Write-Host $s }

L "================ run_log  $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') ================"
L "port $Port @ $Baud   capture ${Seconds}s"

$sp = New-Object System.IO.Ports.SerialPort $Port, $Baud, None, 8, one
$sp.ReadTimeout  = 200
$sp.DtrEnable    = $false
$sp.RtsEnable    = $false
try { $sp.Open() } catch {
    L "OPEN_FAIL ($Port): $($_.Exception.Message)"
    L "  If it says 'Access ... denied': a previous interrupted script still holds the handle."
    L "  Clear it:  Get-CimInstance Win32_Process -Filter \"Name='powershell.exe'\" |"
    L "             ? { \$_.CommandLine -match 'read_serial|uart_send|esp_at|run_log' } | % { Stop-Process -Id \$_.ProcessId -Force }"
    Set-Content $Out $log.ToString() -Encoding ASCII
    exit 1
}

# ---- capture -------------------------------------------------------------------------------
$rx = New-Object System.Text.StringBuilder
$sw = [System.Diagnostics.Stopwatch]::StartNew()
while ($sw.Elapsed.TotalSeconds -lt $Seconds) {
    try { [void]$rx.Append($sp.ReadExisting()) } catch {}
    Start-Sleep -Milliseconds 20
}
try { $sp.Close() } catch {}
try { $sp.Dispose() } catch {}

$lines = ($rx.ToString() -split "`r?`n")

# ---- parse ---------------------------------------------------------------------------------
# [ctl] IDLE tgt=0 | I:0,0 | V:0,0 | PWM:0,0 | C:0,0 | D:0,0 | Y:-31 W:18 | #160 t16800
$re = [regex]'\[ctl\]\s+(?<mode>\S+)\s+tgt=(?<tgt>-?\d+).*?\|\s*I:(?<i1>-?\d+),(?<i2>-?\d+).*?\|\s*V:(?<v1>-?\d+),(?<v2>-?\d+).*?\|\s*PWM:(?<p1>-?\d+),(?<p2>-?\d+).*?\|\s*C:(?<c1>-?\d+),(?<c2>-?\d+).*?\|\s*D:(?<dv>-?\d+),(?<dw>-?\d+).*?\|\s*Y:(?<y>-?\d+)\s+W:(?<w>-?\d+).*?\|\s*#(?<seq>\d+)\s+t(?<t>\d+)'
$rows = New-Object System.Collections.Generic.List[object]
$partial = 0
foreach ($ln in $lines) {
    if ($ln -notmatch '\[ctl\]') { continue }
    $m = $re.Match($ln)
    if (-not $m.Success) { $partial++; continue }
    $g = $m.Groups
    $rows.Add([pscustomobject]@{
        seq = [int]$g['seq'].Value; t_ms = [int]$g['t'].Value
        mode = $g['mode'].Value;    tgt  = [int]$g['tgt'].Value
        i1 = [int]$g['i1'].Value;   i2 = [int]$g['i2'].Value
        v1 = [int]$g['v1'].Value;   v2 = [int]$g['v2'].Value
        pwm1 = [int]$g['p1'].Value; pwm2 = [int]$g['p2'].Value
        c1 = [int]$g['c1'].Value;   c2 = [int]$g['c2'].Value
        dv = [int]$g['dv'].Value;   dw = [int]$g['dw'].Value
        yaw_deg = [double]$g['y'].Value / 10.0
        wz_dps  = [double]$g['w'].Value / 100.0
    })
}

$n = $rows.Count
L ""
L "---- capture ----"
L ("telemetry lines parsed : {0}" -f $n)
if ($partial -gt 0) {
    L ("truncated/unparsed     : {0}   <- half lines = the sender was cut mid-line (check link)" -f $partial)
}
if ($n -lt $MinSamples) {
    L ""
    L ("RESULT: INCONCLUSIVE - only $n samples (need >= $MinSamples).")
    L "  Nothing is proven here - NOT the same as 'no problem'."
    L "  Check: is the car powered / in a mode that prints / is the wireless bridge up"
    L "         (car-side ESP must be in passthrough; PC-side module must be linked)?"
    Set-Content $Out $log.ToString() -Encoding ASCII
    exit 2
}

# ---- packet loss (needs the firmware #<seq>) ------------------------------------------------
$seqFirst = $rows[0].seq
$seqLast  = $rows[$n-1].seq
$expected = $seqLast - $seqFirst + 1
$lost     = $expected - $n
$lossPct  = if ($expected -gt 0) { 100.0 * $lost / $expected } else { 0.0 }

# longest run of consecutive missing sequence numbers
$maxGap = 0; $gapAt = 0
for ($i = 1; $i -lt $n; $i++) {
    $d = $rows[$i].seq - $rows[$i-1].seq - 1
    if ($d -gt $maxGap) { $maxGap = $d; $gapAt = $rows[$i-1].seq }
}

# ---- firmware-side dt ----------------------------------------------------------------------
$dts = New-Object System.Collections.Generic.List[double]
for ($i = 1; $i -lt $n; $i++) {
    $d = $rows[$i].t_ms - $rows[$i-1].t_ms
    $sk = $rows[$i].seq - $rows[$i-1].seq
    if ($sk -eq 1 -and $d -gt 0) { [void]$dts.Add([double]$d) }   # only gap-free neighbours
}
$dtAvg = 0.0; $dtStd = 0.0; $dtMax = 0.0
if ($dts.Count -gt 0) {
    $dtAvg = ($dts | Measure-Object -Average).Average
    $dtMax = ($dts | Measure-Object -Maximum).Maximum
    $acc = 0.0; foreach ($d in $dts) { $acc += ($d - $dtAvg) * ($d - $dtAvg) }
    $dtStd = [Math]::Sqrt($acc / $dts.Count)
}

# ---- motion metrics ------------------------------------------------------------------------
$durS   = ($rows[$n-1].t_ms - $rows[0].t_ms) / 1000.0
$yawNet = $rows[$n-1].yaw_deg - $rows[0].yaw_deg
$yawMin = ($rows | Measure-Object -Property yaw_deg -Minimum).Minimum
$yawMax = ($rows | Measure-Object -Property yaw_deg -Maximum).Maximum
$dC1    = $rows[$n-1].c1 - $rows[0].c1
$dC2    = $rows[$n-1].c2 - $rows[0].c2
$wzPeak = ($rows | ForEach-Object { [Math]::Abs($_.wz_dps) } | Measure-Object -Maximum).Maximum
$vPeak1 = ($rows | ForEach-Object { [Math]::Abs($_.v1) } | Measure-Object -Maximum).Maximum
$vPeak2 = ($rows | ForEach-Object { [Math]::Abs($_.v2) } | Measure-Object -Maximum).Maximum
$modes  = ($rows | Select-Object -ExpandProperty mode -Unique) -join ","

L ""
L "---- link (real loss, from firmware #seq) ----"
L ("seq range              : #{0} .. #{1}  (expected {2})" -f $seqFirst, $seqLast, $expected)
# First line's own numbers answer a question you cannot get any other way:
#   t_ms  = MCU uptime when the first line actually MADE IT THROUGH to the PC
#   seq   = how many lines the MCU had already printed by then (seq-1 never arrived)
# On a cold power-up that is exactly "how long until the wireless link is usable", measured
# by the firmware clock instead of a stopwatch. Only meaningful right after a power cycle.
L ("first line             : #{0} @ t={1} ms (MCU uptime)" -f $seqFirst, $rows[0].t_ms)
# Only interpret this as "time until the link came up" when the capture really started near a
# power-on. If we just attached mid-session (seq already in the thousands) the sentence below
# would be nonsense - the earlier lines were not "lost", we simply were not capturing yet.
if ($seqFirst -le 200) {
    L ("  COLD-BOOT READ: link became usable {0:N1} s after power-on; the {1} line(s) before #{0} never made it out." -f ($rows[0].t_ms / 1000.0), ($seqFirst - 1), $seqFirst)
} else {
    L "  (not a cold boot - capture attached mid-session, so the earlier seq numbers were simply not captured)"
}
L ("received / lost        : {0} / {1}" -f $n, $lost)
L ("LOSS                   : {0:N2} %" -f $lossPct)
L ("longest gap            : {0} line(s){1}" -f $maxGap, $(if ($maxGap -gt 0) { "  (after #$gapAt)" } else { "" }))
L ""
L "---- firmware-side dt (t<ms>, gap-free neighbours only) ----"
L ("dt avg / std / max     : {0:N1} / {1:N1} / {2:N1} ms   (n={3})" -f $dtAvg, $dtStd, $dtMax, $dts.Count)
L "  NOTE dt comes from the MCU clock on purpose - PC arrival times are bursty (UDP packing)."
L ""
L "---- motion scorecard ----"
L ("duration               : {0:N2} s   modes seen: {1}" -f $durS, $modes)
L ("encoder delta L / R    : {0} / {1} counts   DIFF {2}  (ratio {3})" -f $dC1, $dC2, ($dC1 - $dC2), $(if ($dC2 -ne 0) { "{0:N3}" -f ($dC1 / [double]$dC2) } else { "n/a" }))
L ("yaw net change         : {0:N1} deg   (min {1:N1} / max {2:N1})" -f $yawNet, $yawMin, $yawMax)
L ("peak |wz|              : {0:N1} dps" -f $wzPeak)
L ("peak |rpm| L / R       : {0} / {1}" -f $vPeak1, $vPeak2)
L "  Straight-line read: DIFF near 0 and small yaw net change = it went straight."
L "  ENC_COUNTS_PER_MM is still 0 in config.h, so counts are NOT millimetres yet -"
L "  tape-measure the real distance once and back-fill it, then this becomes mm."

if ($Csv -ne "") {
    $rows | Export-Csv -Path $Csv -NoTypeInformation -Encoding ASCII
    L ""
    L ("CSV written            : {0}  ({1} rows)" -f $Csv, $n)
}

L ""
if ($lossPct -gt $MaxLossPct) {
    L ("RESULT: FAIL - loss {0:N2} % exceeds -MaxLossPct {1}" -f $lossPct, $MaxLossPct)
    Set-Content $Out $log.ToString() -Encoding ASCII
    exit 1
}
L ("RESULT: PASS - {0} samples, loss {1:N2} %" -f $n, $lossPct)
Set-Content $Out $log.ToString() -Encoding ASCII
exit 0
